config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  get '/recipes/my_recipes', to: 'recipes#my_recipes'
  get '/recipes/create_recipe', to: 'recipes#new_recipe'
  get '/recipes/:recipe_id', to: 'recipes#show'
  post '/recipes/create', to: 'recipes#create'
  get '/recipes/:recipe_id', to: 'recipes#show'
  post '/recipes/:recipe_id/generate', to: 'recipes#create_shopping_list'
  post '/recipes/:recipe_id/change', to: 'recipes#change'
  post '/recipes/:recipe_id/add', to: 'recipes#add'
  post '/recipes/:recipe_id/remove/:rec_food_id', to: 'recipes#remove'
  post '/recipes/destroy', to: 'recipes#destroy'
  get '/foods', to: 'foods#index'
  post '/foods/create', to: 'foods#create'
  post '/foods/destroy', to: 'foods#destroy'
  get '/inventories', to: 'inventories#index'
  post '/inventories/create', to: 'inventories#create'
  post '/inventories/destroy', to: 'inventories#destroy'
  post 'inventories/:inventory_id/add', to: 'inventories#add'
  post 'inventories/:inventory_id/remove/:inv_fod_id', to: 'inventories#remove'
  get 'inventories/:inventory_id', to: 'inventories#show'
  get '/inventories/compare/:recipes_id/:inventory_id', to: 'inventories#compare'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  has_many :recipe_foods
  belongs_to :user

  def change
    self.is_public = is_public != true
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(is_public: true).order(updated_at: :desc)
  end

  def new_recipe; end

  def show
    @current_user = current_user

    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = @recipe.recipe_foods.all
    @already_inside = @recipe_foods.pluck(:food_id)

    @food_options = Food.where.not(id: @already_inside)
    @inventories = Inventory.where(user_id: @current_user.id) if user_signed_in?
  end

  def my_recipes
    @recipes = Recipe.where(user_id: current_user.id).order(updated_at: :desc)
  end

  def create
    if can? :create, @recipe
      @recipe = Recipe.new
      @recipe.user_id = current_user.id
      @recipe.name = params[:name]
      @recipe.preparation_time = params[:preparation_time]
      @recipe.cooking_time = params[:cooking_time]
      @recipe.description = params[:description]
      @recipe.is_public = params[:is_public] == '1'
      redirect_to('/recipes/my_recipes', notice: 'recipe created succesfully') if @recipe.save
    else
      redirect_to(request.env['HTTP_REFERER'], notice: 'you dont have access')
    end
  end

  def destroy
    if can? :destroy, @recipe
      @recipe = Recipe.find(params[:id])
      @recipe.recipe_foods.each do |recipe_food|
        RecipeFood.delete_by(id: recipe_food.id)
      end
      @recipe.destroy
      redirect_to(request.env['HTTP_REFERER'], notice: 'recipe deleted succesfully')
    else
      redirect_to(request.env['HTTP_REFERER'], notice: 'you dont have access')
    end
  end

  def change
    @recipe = Recipe.find(params[:recipe_id])
    if can? :update, @recipe
      @recipe.is_public = if @recipe.is_public
                            false
                          else
                            true
                          end
      @recipe.save
      redirect_to("/recipes/#{@recipe.id}", notice: 'recipe status to private succesfully')
    else
      redirect_to("/recipes/#{@recipe.id}", notice: 'you dont have access')
    end
  end

  def add
    @current_user = current_user
    @recipe = @current_user.recipes.find(params[:recipe_id])
    if can? :update, @recipe
      rec_food = RecipeFood.new
      @food = Food.find(params[:food])
      rec_food.recipe = @recipe
      rec_food.quantity = params[:quantity]
      rec_food.food = @food
      redirect_to(request.env['HTTP_REFERER']) if rec_food.save
    else
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  def remove
    @recipe = current_user.recipes.find(params[:recipe_id])
    if can? :update, @recipe
      @current_user = current_user
      rec_food = RecipeFood.find(params[:rec_food_id])
      redirect_to(request.env['HTTP_REFERER']) if rec_food.destroy
    else
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  def create_shopping_list
    @recipe = Recipe.find(params[:recipe_id])
    @inventory_id = params[:inventory]
    redirect_to("/inventories/compare/#{@recipe.id}/#{@inventory_id}")
  end
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
end

app/views/recipes/_modal.html.erb
<!-- The Modal1 -->
<div id="myModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
          <span class="close">&times;</span>
        </div>
        <div class="modal-body">
        
        </div>
      </div>
  
  </div>

app/views/recipes/_recipe_food.html.erb
<tr>
  <td><%= recipe_food.food.name %></td>
  <td><%= "#{recipe_food.quantity} #{recipe_food.food.measurement_unit}" %></td>
  <% if can? :update, recipe_food.recipe%>
  <td><%= button_to "Delete", "#{request.url}" +"/remove/#{recipe_food.id}", method: :post, class: 'delete-btn'  %></td>
  <%end %>
</tr>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/index.html.erb
<%= render partial: "shared/header" %>
<div class="container">
  <h1>Public Recipes</h1>
  <div class='create_btn_div'>
    <%= link_to 'Create recipe', recipes_create_recipe_path, class: 'create_btn'%>
  </div>
  <div class='recipes'>
    <% @recipes.each do |recipe|%>
      <div class='recipe'>
        <div class='left'>
          <a href=<%="recipes/"+recipe.id.to_s %> >
            <p class='r-name'><%= recipe.name%> </p>
          </a>
          <p class='author-name'>By: <%= User.find_by(id: recipe.user_id).name%></p>
        </div>
        <div class='right'>
          <p class='r-description'><%= recipe.description%></p>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/recipes/my_recipes.html.erb
<%= render partial: "shared/header" %>
<div class="container">
  <h1>My Recipes</h1>
  <div class='create_btn_div'>
    <%= link_to 'Create recipe', recipes_create_recipe_path, class: 'create_btn'%>
  </div>
  <div class='recipes'>
    <% @recipes.each do |recipe|%>
      <div class='recipe'>
        <div class='left'>
          <a href=<%=recipe.id.to_s %> >
            <p class='r-name'><%= recipe.name%> </p>
          </a>
          <%= button_to "Delete", recipes_destroy_path(id: recipe.id), method: :post, class: 'delete-btn'  %>
        </div>
        <div class='right'>
          <p class='r-description'><%= recipe.description%></p>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/recipes/new_recipe.html.erb
<div class='form-page'>
  <%= form_with model: @recipe, url: recipes_create_path do |form|%>
    <div class="form-container">
      <h1>Create a new recipe</h1>
      <div class="separation-bar">
      </div>
      <div class='field'>
        <%= form.label :name, 'Name' %>
        <%= form.text_field :name, class: 'input' %>
      </div>
      <div class='field'>
        <%= form.label :description, 'Description' %>
        <%= form.text_area :description, class: 'input' %>
      </div>
      <div class='field'>
        <%= form.label :cooking_time, 'Cooking time(mins)' %>
        <%= form.number_field :cooking_time, class: 'input' %>
      </div>
      <div class='field'>
        <%= form.label :preparation_time, 'Preparation time(mins)' %>
        <%= form.number_field :preparation_time, class: 'input'%>
      </div>
      <div class='field'>
        <%= form.label :is_public, 'make it public?' %>
        <div>
          <%= form.check_box :is_public %>
        </div>
      </div>
      <div>
        <%= form.submit "Submit", class: 'create_btn'%>
      </div>
      <div class='go-back'>
        <a href= javascript:history.back() class='delete-btn'>
          Go Back
        </a>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<%= render partial: "shared/header" %>
<% if user_signed_in? %>
<div class="modal-background">
    <div class="modal">
      <div class="modal-header">
        <h2 class="modal-title">Generating shopping list</h2>
        <div class="X">
          <p >X</p>
        </div>
      </div>
      <div class='modal-body'>
      <% if @current_user.inventories.length > 0 %>
        <h3>Choose an inventory to use</h3>
        <%= form_with  url: "/recipes/#{@recipe.id}/generate" do |form| %>
          <%= form.label :inventory %>
          <%= form.collection_select :inventory, @inventories ,:id , :name %>
          <%= form.submit "Generate", class: "create_btn" %>
        <% end %>
        <% else %>
        <h3>There is not inventory to use, create one<a href="/inventories">here</a></h3>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
<div class='container'>
  <h1><%= @recipe.name %></h1>
  <div class="recipe_d">
    <div class="recipe_d_h">
      <p>preparation time: <%= @recipe.preparation_time%>mins</p>
      <div>
      <% if can? :update, @recipe%>
        <% if @recipe.is_public%>
        <%= button_to "Public", "/recipes/#{@recipe.id}/change", class: 'create_btn' %>
        <% else %>
        <%= button_to "Private", "/recipes/#{@recipe.id}/change", class: 'create_btn' %>
        <% end %>
      <% else %> 
      <% if @recipe.is_public%>
        <h3>Public</h3>
        <% else %>
        <%= button_to "Private", "/recipes/#{@recipe.id}/change", class: 'create_btn' %>
        <h3>Private</h3>
        <% end %>
      <% end %>
      </div>
    </div>
    <p>cooking time: <%= @recipe.cooking_time%>mins</p>
    <h3>steps goes here</h3>
    <p> <%= @recipe.description %> </p>
    <div class="recipe_b_s">
    <% if user_signed_in? %>
      <%= button_tag "Generate shopping list", id: "modal-displayer" , class: 'create_btn down'%>
    <%end%>
      <% if can? :update, @recipe%>
      <% if(@food_options.length > 0) %>
<%= form_with model: @recipe_food, class: "inventory-food-form", url: "/recipes/#{@recipe.id}/add" do |form| %>
  <h3 class="">Add Food: </h3>
  <%= form.label :food %>
  <%= form.collection_select :food, @food_options ,:id , :name %>
  <%= form.label :quantity %>
  <%= form.number_field :quantity, min: 1, value: 1 %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= form.submit "Submit", class: "submit" %>
  <% end %>
  <% else %>
  <h3 class="">There is not food to add </h3>
  <% end %>
    <% end %>
        </div>
    <div class="separation-bar">
    </div>
    <% if(@recipe_foods.length > 0) %>
      <table>
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity Name</th>
            <% if can? :update, @recipe%>
            <th>Action</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @recipe.recipe_foods.each do |recipe_food| %>
            <%= render partial: "recipes/recipe_food", object: recipe_food %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>
<%= javascript_pack_tag 'modal_js' %>