config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  get '/recipes/my_recipes', to: 'recipes#my_recipes'
  get '/recipes/create_recipe', to: 'recipes#new_recipe'
  get '/recipes/:recipe_id', to: 'recipes#show'
  post '/recipes/create', to: 'recipes#create'
  get '/recipes/:recipe_id', to: 'recipes#show'
  post '/recipes/:recipe_id/generate', to: 'recipes#create_shopping_list'
  post '/recipes/:recipe_id/change', to: 'recipes#change'
  post '/recipes/:recipe_id/add', to: 'recipes#add'
  post '/recipes/:recipe_id/remove/:rec_food_id', to: 'recipes#remove'
  post '/recipes/destroy', to: 'recipes#destroy'
  get '/foods', to: 'foods#index'
  post '/foods/create', to: 'foods#create'
  post '/foods/destroy', to: 'foods#destroy'
  get '/inventories', to: 'inventories#index'
  post '/inventories/create', to: 'inventories#create'
  post '/inventories/destroy', to: 'inventories#destroy'
  post 'inventories/:inventory_id/add', to: 'inventories#add'
  post 'inventories/:inventory_id/remove/:inv_fod_id', to: 'inventories#remove'
  get 'inventories/:inventory_id', to: 'inventories#show'
  get '/inventories/compare/:recipes_id/:inventory_id', to: 'inventories#compare'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<header class="header">
<div class="nav">
  <input type="checkbox" id="nav-check">
  <div class="nav-header">
    <div class="nav-title">
      Recipe App
    </div>
  </div>
  <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>
  
  <div class="nav-links">
    <a href="/foods">Foods</a>
    <a href="/">Recipes</a>
  <% if user_signed_in? %>
    <a href="/recipes/my_recipes">My Recipes</a>
    <a href="/inventories">Inventories</a>
    <%= link_to("Logout", destroy_user_session_path, method: :delete)%>
    <%else%>
    <%= link_to('Login', new_user_session_path) %>  
  <% end %>
  </div>
</div>
</header>
    <% flash.each do |name, message| %>
      <div class="<%= name %>"><%= message %></div>
    <% end %>

app/views/shared/_navigation.html.erb
<nav>
  <ul class = 'nav-ul'>
        <li class = "nav-list">
          <%= link_to "Foods", foods_path, class: change_color_when_active(foods_path) %>
        </li>
      <li class = "nav-list">
        <%= link_to "My recipes", recipes_path, class: change_color_when_active(recipes_path)%>
      </li>
      <li class = "nav-list">
        <%= link_to "Public recipes", public_recipes_path, class: change_color_when_active(public_recipes_path)%>
      </li>
  </ul>
</nav>

app/views/shared/_sign_options_nav.html.erb
<ul class = 'sign-nav-ul'>
  <% if user_signed_in? %>
    <li class = "sign-nav-list">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </li>
    <li class = "sign-nav-list">
      <%= link_to "Edit Profile", edit_user_registration_path %>
    </li>
  <% else %>
    <li class = "sign-nav-list">
      <%= link_to "Sign In", new_user_session_path %>
    </li>
    <li class = "sign-nav-list">
      <%= link_to "Sign Up", new_user_registration_path %>
    </li>
  <% end %>
</ul>