config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  get '/recipes/my_recipes', to: 'recipes#my_recipes'
  get '/recipes/create_recipe', to: 'recipes#new_recipe'
  get '/recipes/:recipe_id', to: 'recipes#show'
  post '/recipes/create', to: 'recipes#create'
  get '/recipes/:recipe_id', to: 'recipes#show'
  post '/recipes/:recipe_id/generate', to: 'recipes#create_shopping_list'
  post '/recipes/:recipe_id/change', to: 'recipes#change'
  post '/recipes/:recipe_id/add', to: 'recipes#add'
  post '/recipes/:recipe_id/remove/:rec_food_id', to: 'recipes#remove'
  post '/recipes/destroy', to: 'recipes#destroy'
  get '/foods', to: 'foods#index'
  post '/foods/create', to: 'foods#create'
  post '/foods/destroy', to: 'foods#destroy'
  get '/inventories', to: 'inventories#index'
  post '/inventories/create', to: 'inventories#create'
  post '/inventories/destroy', to: 'inventories#destroy'
  post 'inventories/:inventory_id/add', to: 'inventories#add'
  post 'inventories/:inventory_id/remove/:inv_fod_id', to: 'inventories#remove'
  get 'inventories/:inventory_id', to: 'inventories#show'
  get '/inventories/compare/:recipes_id/:inventory_id', to: 'inventories#compare'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/food.rb
# frozen_string_literal: true

class Food < ApplicationRecord
  has_many :inventory_foods
  has_many :recipe_foods
  belongs_to :user
end

app/controllers/foods_controller.rb
# frozen_string_literal: true

class FoodsController < ApplicationController
  def index
    @foods = Food.all.order(created_at: :desc)
    @current_user = current_user
    @measurement = [%w[kg kg], %w[gramme gramme], %w[unit unit]]
  end

  def create
    @food = Food.new
    @food.user_id = current_user.id
    @food.name = params[:name]
    @food.measurement_unit = params[:measurement_unit]
    @food.price = params[:price]
    redirect_to(request.env['HTTP_REFERER'], notice: 'food created succesfully') if @food.save
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to(request.env['HTTP_REFERER'], notice: 'food deleted succesfully')
  end
end

app/helpers/foods_helper.rb
# frozen_string_literal: true

module FoodsHelper
end

app/views/foods/_food.html.erb
    <tr>
      <td><%= food.name %></td>
      <td><%= "#{food.measurement_unit}" %></td>
      <td><%= "#{food.price}" %></td>
      <td>
      <% if @current_user != nil %>
        <% if(food.user_id == @current_user.id) %>
          <%= button_to "Delete", foods_destroy_path(id: food.id), method: :post, class: 'delete-btn'  %>
        <% end %>
      <% end %>
      </td>
    </tr>

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/index.html.erb
<%= render partial: "shared/header" %>
<div class="container">
  <h1 class="inventory-title">Foods</h1>
  <% if @current_user != nil %>
    <%= form_with model: @food, class: "inventory-food-form", url: foods_create_path do |form| %>
      <h3 class="">Create Food: </h3>
      <%= form.label :name, 'Name' %>
      <%= form.text_field :name%>
      <%= form.label :measurement_unit %>
      <%= form.select :measurement_unit, @measurement%> 
      <%= form.label :price, 'Unit price' %>
      <%= form.number_field :price, min: 1, value: 1 %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= form.submit "Submit", class: "submit" %>
    <% end %>
    <div class="separation-bar"></div>
  <% end %>
  <% if(@foods.length > 0) %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Measurement Unit</th>
        <th>Unit Price($)</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <%= render partial: "foods/food", object: food %>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>

app/views/foods/new.html.erb
<div class = add-food-form>
  <%= form_with model: [current_user.foods.build], class: "form" do |f| %>
      <%= f.label :food_name  %>
      <%= f.text_field :name, autofocus: true, placeholder: 'Bananas'%>

      <%= f.label :measurment_units %>
      <%= f.text_field :measurement_units, placeholder: 'grams/kilo/piece'%>

      <%= f.label :price %>
      <%= f.number_field :price, placeholder: '20$', min: 0 %>
    <p>
      <%= f.submit 'Add food', class: 'add-food-btn' %>
    </p>
  <% end %>

<ul class = "food-form-errors">
    <%@food.errors.full_messages.each do |msg|%>
      <li class = "food-form-errors-list">
        <%= msg%>
      </li>
    <%end%>
</ul>

  <div class = "back-btn-holder">
    <button class = "back-btn">
      <%= link_to 'Back', foods_path%>
    </button>
  </div>
</div>